# Generated by Django 5.0.3 on 2024-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mithusbows', '0002_adminregmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='mithusbows/static')),
                ('itemname', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
