# Generated by Django 5.0.3 on 2024-04-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mithusbows', '0007_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
