# Generated by Django 5.0.3 on 2024-04-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mithusbows', '0008_item_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cart',
            new_name='count',
        ),
    ]
